default_platform(:android)

platform :android do
  desc "Submit a new Beta build to Google Play"
  lane :beta do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
    supply(
      json_key: ENV["PLAYSTORE_JSON"], # либо путь к файлу
      track: "beta",
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH] || "app/build/outputs/apk/release/app-release.apk"
    )
  end
end
